# **Pandas Case study**

In [ ]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = sns.load_dataset("titanic")

In [ ]:
data.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# saving datafame into csv file
data.to_csv('titanic.csv')

In [ ]:
# basic satistics or summary
data.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
data.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# droping few coloumns and make a new data set

data.drop(['deck', 'embark_town', 'alone'], axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,no
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,no

In [ ]:
data.value_counts(['survived'])

survived
0           549
1           342
Name: count, dtype: int64

In [ ]:
data.groupby(['sex', 'class'])[['survived', 'age', 'sibsp', 'parch', 'fare']].mean()

<ipython-input-13-e38ec79bd8dc>:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby(['sex', 'class'])[['survived', 'age', 'sibsp', 'parch', 'fare']].mean()

               survived        age     sibsp     parch        fare
sex    class
female First   0.968085  34.611765  0.553191  0.457447  106.125798
       Second  0.921053  28.722973  0.486842  0.605263   21.970121
       Third   0.500000  21.750000  0.895833  0.798611   16.118810
male   First   0.368852  41.281386  0.311475  0.278689   67.226127
       Second  0.157407  30.740707  0.342593  0.222222   19.741782
       Third   0.135447  26.507589  0.498559  0.224784   12.661633

In [ ]:
data[data['age']< 18]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,0,3,male,4.0,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
852,0,3,female,9.0,1,1,15.2458,C,Third,child,False,NaN,Cherbourg,no,False
853,1,1,female,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False
869,1,3,male,4.0,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True

In [ ]:
#children
data[data['age']< 18].groupby(['sex', 'class'])[['survived', 'age', 'sibsp', 'parch', 'fare']].mean()

<ipython-input-17-bab670220643>:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data[data['age']< 18].groupby(['sex', 'class'])[['survived', 'age', 'sibsp', 'parch', 'fare']].mean()

               survived        age     sibsp     parch        fare
sex    class
female First   0.875000  14.125000  0.500000  0.875000  104.083337
       Second  1.000000   8.333333  0.583333  1.083333   26.241667
       Third   0.542857   8.428571  1.571429  1.057143   18.727977
male   First   1.000000   8.230000  0.500000  2.000000  116.072900
       Second  0.818182   4.757273  0.727273  1.000000   25.659473
       Third   0.232558   9.963256  2.069767  1.000000   22.752523